### ISSUE TITLE
scope

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/blog#1]
@strengejacke What do you think 😄 ? We can just add Rmd files in the content/posts folder, run `blogdown::serve_site()` command and push...

**Comment by strengejacke** [comment]
That's easy! Can we register this blog at r-bloggers?

**Comment by DominiqueMakowski** [comment]
I'll fill the form to do so :) Any idea about a first post?

**Comment by DominiqueMakowski** [comment]
We need first to add a link to rbloggers. We could do it in a new post about "resources to learn R" with a short list of interesting and relevant links to learn R. Maybe we can work on new blogposts in branches, so that we have full control over when to merge it to master (and send it to rbloggers)?

**Comment by strengejacke** [comment]
Yes, sounds good. I think the link to r-bloggers needs to be a permanent link, in the siderbar or so.

**Comment by DominiqueMakowski** [comment]
> I linked to r-bloggers.com from my blog's blogroll? *
> Bloggers who wish to join should *first* give a blogroll link to https://www.r-bloggers.com. Blog's without a linkback will not be added to the site (this is checked before a feed is added - so please make sure this is o.k.). R-bloggers offer you a link-back from it's blogroll (at random) and from the contributors page, **on top of the linkback within your posts on the site (p.s.: it is even better to add to your sidebar the titles of the r-bloggers feed: http://feeds.feedburner.com/RBloggers )**

I think we could try first with a link in the post (I dont see any location to put it nicely in the sidebar...)?

**Comment by strengejacke** [comment]
Do we only need to push the rmd, or the knitted html as well?

**Comment by DominiqueMakowski** [comment]
I think that when `blogdown::serve_site()`, the html is copied and transformed into the `static` folder. So the original html of the `content` folder is not required. However, it is my first time using blogdown, so I am not sure of anything!

(now is the time to try everything before it is hooked up to rbloggers)

**Comment by DominiqueMakowski** [comment]
I am not sure if `serve_site()` re-knits the rmd every time. I am currently working on a machine learning based function for `parameters`, that it might be good to document via a blogpost. But the code takes forever to run (I'll have to run it on my uni's servers). So I hope that `serve_site` will use the "already-knitted" html of the content folder if available instead of reknitting the rmd.
