### ISSUE TITLE
Game of Thrones bait

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/blog#10]
(just kidding of course:) since GoT madness just started again, we should make a post titled "Do you know which Game of Thrones character dies next?". In which we say "*Well, we neither*. However, have you heard of the easystats project?" and then go on and present easystats. I bet such post would be clicked on a lot 😅 😅

**Comment by strengejacke** [comment]
haha, sounds good! :-) Could also be a "test post" to see whether the URL-bug at r-bloggers is fixed.

**Comment by DominiqueMakowski** [comment]
Guess it's too late now 👑
