### ISSUE TITLE
people

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/blog#17]
@pdwaggoner @mattansb could you guys add yourselves in the [monster hunters](https://github.com/easystats/blog/blob/master/content/portfolio/people.md) list.

**Comment by strengejacke** [comment]
we need a ghostbusters-alike logo for that subpage ;-)
Maybe someday we can also make a movie. :-D

**Comment by DominiqueMakowski** [comment]
🎵 *There's something strange... in the R console... who you gonna call? the easystats package!* 🎵

**Comment by mattansb** [comment]
Add this to the monster hunters page??
"Sure, your r package has a hex-logo, but does it have a jingle??"
