### ISSUE TITLE
Fix broken URLs

### ISSUE THREAD

**Issue by strengejacke** [easystats/blog#28]
@DominiqueMakowski any ideas how to quickly restore or fix the broken URLs? Many blog pages are affected, I think, though I fixed some of them.

**Comment by DominiqueMakowski** [comment]
which URLs are broken?

**Comment by strengejacke** [comment]
It's mostly images that are missing, and the link in the left side bar to the "home" is not correct, I think. 

e.g. the left sidebar here:
https://easystats.github.io/blog/posts/bayestestr_v2/

images here:
https://easystats.github.io/blog/posts/see_presentation/
https://easystats.github.io/blog/posts/bayestestr_distribution/
https://easystats.github.io/blog/posts/bayestestr_rnorm_perfect/
https://easystats.github.io/blog/posts/bayestestr_presentation/

I think _all_ existing files that were changed by `build_site()` and where absolute URLs were replaced by relative URLs may not work (https://github.com/easystats/blog/pull/27/files).

**Comment by strengejacke** [comment]
I fixed the most important ones yesterday (i.e. the new blog post, etc.) to have it worked, since it's now also published on r-bloggers.

**Comment by DominiqueMakowski** [comment]
Oh yes, this morning I checked your last post and the result on rbloggers and everything seemed to be fine but indeed there are some issues in the other posts. I'll check that

**Comment by DominiqueMakowski** [comment]
I am trying to fix it but I am not sure where to look for the cause of this... what did we change... it worked previously

**Comment by strengejacke** [comment]
It all happened after you ran `blogdown::build_site()` and [committed quite some amount of files](https://github.com/easystats/blog/pull/27/commits/a58f19c3559020e445e64c0edc65af60c8ba046a)... ;-)

**Comment by DominiqueMakowski** [comment]
no I know but previously it didn't destroy everything

it's okayI think I found...

**Comment by DominiqueMakowski** [comment]
I reverted @humanfactors suggestion of cannonicalURL to false...... 😁  (I have no idea what it does but it seems to have worked in solving the issue)
