### ISSUE TITLE
Announcing parameters and see updates

### ISSUE THREAD

**Issue by strengejacke** [easystats/blog#31]
I'd like to write two to three posts, introducing some of the news that shipped with the recent updates from _parameters_ and _see_, mostly combinining both packages (accompanied by _bayestestR_, when showing new plotting-functions in _see_). What do you think?

**Comment by strengejacke** [comment]
Ok, and I have to recall how to submit/commit all the rmd-stuff... 😕

**Comment by DominiqueMakowski** [comment]
totally agree, there's so many things that are worth showcasing (https://github.com/easystats/blog/issues/14)! If only we had more time!

> Ok, and I have to recall how to submit/commit all the rmd-stuff... 

^^ In theory if you follow the README steps everything should be alright. I have faith

**Comment by IndrajeetPatil** [comment]
I think this is out of date by now.
