### ISSUE TITLE
content

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/blog#5]
The maintainer of R-bloggers asked to add a bit more content first before he connects it to the platform. I'll re-adapt some of the posts from the psycho blog and add them here.

**Comment by strengejacke** [comment]
Sounds good! So, r-bloggers are happy to accept our blog "as is" (w/o perma-link in sidebar)?

**Comment by DominiqueMakowski** [comment]
I managed to add the resources link to the sidebar :)

There were some issues with the RSS feed (god internet is very complicated :p), but I found I managed to fix them. Once I have confirmation that we are hooked to r-bloggers, I will try adding us also to:

- https://rweekly.org/submit
- https://awesome-blogdown.com/

**Comment by DominiqueMakowski** [comment]
> Dear Dom, I'm happy to report that I've just added your feed https://easystats.github.io/blog/categories/r/index.xml to R-bloggers.com, welcome onboard! I am happy adding your blog, it looks great.

I think we're in :)

**Comment by DominiqueMakowski** [comment]
- [ ] https://rweekly.org/submit

The blog has been submitted. Waiting for an answer I guess.

- [x] https://awesome-blogdown.com/

The [PR](https://github.com/sellorm/awesome-blogdown/pull/62) is in process.

**Comment by DominiqueMakowski** [comment]
It just made its way on [r-bloggers](https://www.r-bloggers.com/a-unified-syntax-for-accessing-models-information/), but not on the top for some reasons 😅
