### ISSUE TITLE
How to release a blog post

### ISSUE THREAD

**Issue by strengejacke** [easystats/blog#7]
1) Add a `.Rmd` to `contents`
2) run `blogdown::serve_site()` so it builds the corresponding html and shows the site locally
3) if everything is ok, just push everything

**Comment by DominiqueMakowski** [comment]
Maybe we should put this in the README

**Comment by strengejacke** [comment]
Yes, probably better...

**Comment by DominiqueMakowski** [comment]
Added a first pass, might need to be improved if not clear enough :)

**Comment by strengejacke** [comment]
Thanks, that's ok! More a reminder for me anyway. ;-)
